# We are not using any mechanism to ensure the database is up and ready for a connection before the application server is up
version: "3.9"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: example
